### ISSUE TITLE
Improve asi loader from openvhook

### ISSUE THREAD

**Issue by TheGreenBandit** [tupoy-ya/YimMenu#13]
https://github.com/JackD111/OpenVHook

**Comment by tupoy-ya** [comment]
What is the problem with the current implementation, what do i need to improve.
Can you please follow the issue template because i can't understand what you want.
Same for #14

**Comment by TheGreenBandit** [comment]
with this you wouldnt have to remove online checks from things such as menyoo, and menyoo doesnt work curreently with the asi loader you have setup but will with this

**Comment by tupoy-ya** [comment]
Menyoo works fine with current scripthook for me, but it uses detected model spawn bypass, detected natives, it's detected by the sigscanner, and breaks missions, it also has something else wish causes modder events to be sent. I used to path it and play online but it wasn't sigged and didn't send modder events then. And now i just gave up maintaining it.

**Comment by TheGreenBandit** [comment]
yeah i get it

**Comment by tupoy-ya** [comment]
Made a public Menyoo fork which "should" be safe for online use.
https://github.com/tupoy-ya/MenyooMP

**Comment by TheGreenBandit** [comment]
Really? Damn

**Comment by TheGreenBandit** [comment]
> Made a public Menyoo fork that "should" be safe for online use.
> 
> https://github.com/tupoy-ya/MenyooMP

Thanks
