### ISSUE TITLE
Improve persist car from files from Lord Griffin

### ISSUE THREAD

**Issue by TheGreenBandit** [tupoy-ya/YimMenu#14]
https://github.com/navmodder/Nenyooo-Modded-Vehicle-Sponner

**Comment by TheGreenBandit** [comment]
I tried doing it myself but a part broke somehow in the menu

**Comment by TheGreenBandit** [comment]
![BigBaseV2 - Microsoft Visual Studio 10_15_2022 3_41_16 PM](https://user-images.githubusercontent.com/106003542/196005178-b62dfec9-32ae-4578-94e2-af038e4d6bbd.png)
![BigBaseV2 - Microsoft Visual Studio 10_15_2022 3_41_07 PM](https://user-images.githubusercontent.com/106003542/196005179-8b706997-1ddc-434f-9bff-c8af1a02e279.png)

**Comment by TheGreenBandit** [comment]
would add collision, visibility, and invincibility options to vehicle files, say u wanted to attach a cow to a car and make the car invisible so it looks like you are riding the cow, you could do that, invincibility would stop objects from catching on fire etc, collision would allow if u attached a ramp to a truck the ramp would have collision

**Comment by tupoy-ya** [comment]
That would be nice to have but i don't think the repo you linked is GPL2 compatible.
It's also something that should be added to base YimMenu because it enhances a feature that's already implemented there.

**Comment by TheGreenBandit** [comment]
i mean u can implement it into yimmenu cause me trying broke it somehow lmao

**Comment by TheGreenBandit** [comment]
if u look into simple menu on unknown cheats, i saw a ytd loader in there, tried implementing it into menu too, also broke it somehow (link if u want: https://www.unknowncheats.me/forum/grand-theft-auto-v/511918-simple-menu-updated-v1-61-a.html )

**Comment by tupoy-ya** [comment]
What are you trying to do with YTD loader? YimMenu uses ImGui so i don't see a reason to have YTD loader unless you are making a NativeUi interface or hooking something like `am_pi_menu`.

**Comment by tupoy-ya** [comment]
> would add collision, visibility, and invincibility options to vehicle files, say u wanted to attach a cow to a car and make the car invisible so it looks like you are riding the cow, you could do that, invincibility would stop objects from catching on fire etc, collision would allow if u attached a ramp to a truck the ramp would have collision

I can try adding these features myself without using the files you linked because Nenyooo is proprietary and i can't use it's code.

**Comment by TheGreenBandit** [comment]
> What are you trying to do with YTD loader? YimMenu uses ImGui so i don't see a reason to have YTD loader unless you are making a NativeUi interface or hooking something like `am_pi_menu`.

A ytd loader would let u change the textures of cars, say u had a blimp, u could change the picture on it to something else, say u had a car, u could change its texture to anything else
